### PR TITLE
修复运行时持续报错，无法粘贴openid的bug

### PR DESCRIPTION
**Pull request by shiyan-liu**
原：
f3e8050f2d29edecd9b5984c26ae0f68
改后：
dd7925ebf6e260176e8d1bd200ac77b7
7b550bdf07a0968287de950a3f7c4557

### CODE REVIEW

**Comment by ManiaciaChao** [comment]
Bro, you should blur your name in the screenshot 🤣

And for this problem, just delete the entire "clipboard" field from your config. You don't need to modify the code itself. 

Thanks for PR anyway.

**Comment by shiyan-liu** [comment]
收到了，不过剪贴板似乎有bug？如图一

**Comment by ManiaciaChao** [comment]
> 收到了，不过剪贴板似乎有bug？如图一

`pbcopy` / `pbpaste` is only available on macOS. You need to replace the command conditionally.

On Linux, you can use `xclip` (for x11) or `wl-clipboard` (for Wayland)
On Windows, you should execute `Set-Clipboard` / `Get-Clipboard` from powershell.

**Comment by shiyan-liu** [comment]
> > 收到了，不过剪贴板似乎有bug？如图一
> 
> `pbcopy` / `pbpaste` is only available on macOS. You need to replace the command conditionally.
> 
> On Linux, you can use `xclip` (for x11) or `wl-clipboard` (for Wayland) On Windows, you should execute `Set-Clipboard` / `Get-Clipboard` from powershell.

感谢(*^▽^*)

**Pull request closed without merging**
